import 'dotenv/config'
import { pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core'
import { AppBuilder, INJECTION_TOKENS, HardDeleteDataSource, TokenHelper } from '@gear5/core'
import type { DbConfig, IFilterBuilder, WriteCriteria } from '@gear5/core'

// ─────────────────────────────────────────────────────────────────────────────
// 1. DRIZZLE SCHEMA DEFINITION
// ─────────────────────────────────────────────────────────────────────────────
// This is a simple Drizzle schema definition for a "users" table. It includes an auto-incrementing primary key, a name, an email (which must be unique), and a timestamp for when the record was created.
export const usersTable = pgTable('users', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  createdAt: timestamp('created_at').defaultNow(),
})

type UserDto = typeof usersTable.$inferInsert


// ─────────────────────────────────────────────────────────────────────────────
// 2. FILTER BUILDER IMPLEMENTATION
// ─────────────────────────────────────────────────────────────────────────────
// This is a simple implementation of the IFilterBuilder interface. It provides methods to build various types of query criteria and projections based on the provided WriteCriteria. The actual logic for building these criteria would depend on the specific requirements of your application and database schema.
class FilterBuilder implements IFilterBuilder {
  buildFilter(criteria: WriteCriteria): unknown {
    // Implement your filter building logic here
    return criteria as unknown
  }

  buildFindCriteria<WriteCriteria>(criteria: WriteCriteria): unknown {
    // Implement your find criteria building logic here
    return criteria as unknown
  }

  buildUpdateCriteria<WriteCriteria>(criteria: WriteCriteria): unknown {
    // Implement your update criteria building logic here
    return criteria as unknown
  }

  buildDeleteCriteria<WriteCriteria>(criteria: WriteCriteria): unknown {
    // Implement your delete criteria building logic here
    return criteria as unknown
  }

  buildQueryCriteria<WriteCriteria>(criteria: WriteCriteria, params?: Record<string, unknown>): unknown {
    // Implement your query criteria building logic here
    return { ...criteria, ...params } as unknown
  }

  buildProjections(cols: string[] | undefined): unknown {
    // Implement your projections building logic here
    return cols as unknown
  }
}
  
// ─────────────────────────────────────────────────────────────────────────────
// 3. DEMO FUNCTION
// ─────────────────────────────────────────────────────────────────────────────
// This function demonstrates how to set up a database connection using the AppBuilder, register a custom data source, and perform a simple insert operation into the "users" table. It handles errors gracefully and ensures that the process exits cleanly after execution.
// ─────────────────────────────────────────────────────────────────────────────
async function runDemo() {
  console.log('🚀 Avvio Demo 01: Database e DataSource...\n')

  const builder = new AppBuilder()

  // A. DATABASE MODULE CONFIGURATION
  builder.addDb((opts: DbConfig) => {
    if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL missing!')
    opts.connectionString = process.env.DATABASE_URL
    opts.tables = { users:  usersTable }
  })

  // B. REGISTRATION OF OUR CUSTOM DATASOURCE IN THE CONTAINER
  // We create a local token for this dependency
  const USER_DS_TOKEN = TokenHelper.createToken<HardDeleteDataSource<UserDto, any>>('USER_DATA_SOURCE')
  const FILTER_BUILDER_TOKEN = TokenHelper.createToken<IFilterBuilder>('FILTER_BUILDER')
  
  // We tell the container to inject the IDbClient generated by the DbModule into our DataSource
  builder.addSingleton(FILTER_BUILDER_TOKEN, FilterBuilder, [])

  builder.addTransientFactory(USER_DS_TOKEN, (c) => {
    const dbClient = c.resolve(INJECTION_TOKENS.DB_CLIENT)
    return new HardDeleteDataSource<UserDto, any>(dbClient, 'users', c.resolve(FILTER_BUILDER_TOKEN))
  })

  try {
    // C. BUILD THE CONTAINER (WHICH WILL INVOKE THE DB MODULE FACTORY)
    const container = await builder.build()
    console.log('✅ Framework configured and modules started.')

    // D. RESOLVE OUR DATASOURCE
    const userDataSource = container.resolve<HardDeleteDataSource<UserDto, any>>(USER_DS_TOKEN)

    // E. ACTUAL TEST
    const newUserDto: UserDto = {
      name: "Admin Demo",
      email: `demo.${Date.now()}@example.com`
    }
    const newUser = await userDataSource.insert(newUserDto, undefined)

    console.log('🎉 User successfully created in the Database!')
    console.log('👤 Data:', newUser)

  } catch (error) {
    console.error('❌ Error during execution:', error)
  } finally {
    process.exit(0)
  }
}

runDemo()