import type { InjectionToken, LogLevel, Optional } from '@/shared'

import type { ILoggerClient } from './ilogger-client.contracts'

/**
 * @description Interface defining the structure of a logger configuration object. This includes properties such as the minimum log level that should be captured by the logger. The log level determines the severity of log messages that will be processed and forwarded to the logging clients, allowing developers to control the verbosity of logs based on the needs of the application and its operational context.
 */
export interface LoggerConfig {
  /**
   * @description
   * The level property specifies the minimum log level that should be captured by the logger. Log levels typically include DEBUG, INFO, WARN, and ERROR, with each level representing a different severity of log messages. By setting the log level, developers can control the verbosity of the logs and ensure that only relevant information is captured based on the needs of the application and its operational context.
   */
  level: Optional<LogLevel>

  console?: boolean

  sentry?: {
    isEnabled: boolean
    config: Optional<SentryLoggerConfig>
  }

  pino?: {
    isEnabled: boolean
    config: Optional<PinoLoggerConfig>
  }

  customLoggers?: Optional<InjectionToken<ILoggerClient>[]>
}

/**
 * @description Interface defining the structure of the configuration object required to initialize a logger. This includes properties such as the Data Source Name (DSN) for connecting to the logging service, the environment in which the application is running (e.g., development, production), and the minimum log level that should be captured by the logger.
 */
export interface SentryLoggerConfig {
  /**
   * @description
   * The Data Source Name (DSN) is a string that provides the necessary information for the logger to connect to the logging service. It typically includes the protocol, public key, secret key, host, and project ID. The DSN is essential for authenticating and routing log data to the correct destination in the logging infrastructure.
   */
  dsn: Optional<string>
  /**
   * @description
   * The environment property indicates the context in which the application is running, such as 'development', 'staging', or 'production'. This information can be used by the logging service to categorize and filter logs based on the environment, allowing for better organization and analysis of log data.
   */
  environment: Optional<string>
}

/**
 * @description Interface defining the structure of the configuration object required to initialize a Pino logger. This includes properties such as the destination for log output, which can be a file path, a stream, or a logging service endpoint. By configuring the destination, developers can control where the log data is stored or sent, enabling integration with various logging infrastructures and facilitating log management and analysis.
 */
export interface PinoLoggerConfig {
  /**
   * @description
   * The destination property specifies the output destination for the logs generated by the Pino logger. This can be a file path, a stream, or a logging service endpoint. By configuring the destination, developers can control where the log data is stored or sent, enabling integration with various logging infrastructures and facilitating log management and analysis.
   */
  destination: Optional<string>
}
